import React from "react";
 
export default class RegistrationCertificate extends React.Component {
  render() {
    return (
      <table>
        <thead>
          <th>Test</th>
          <th>Print</th>
          <th>On</th>
          <th>ReactJS</th>
        </thead>                
        <tbody>
          <tr>
              <td>Test</td>
              <td>Print</td>
              <td>On</td>
              <td>ReactJS</td>
          </tr>
          <tr>
              <td>Test</td>
              <td>Print</td>
              <td>On</td>
              <td>ReactJS</td>
          </tr>
          <tr>
              <td>Test</td>
              <td>Print</td>
              <td>On</td>
              <td>ReactJS</td>
          </tr>
          <tr>
              <td>Test</td>
              <td>Print</td>
              <td>On</td>
              <td>ReactJS</td>
          </tr>
          <tr>
              <td>Test</td>
              <td>Print</td>
              <td>On</td>
              <td>ReactJS</td>
          </tr>
          <tr>
              <td>Test</td>
              <td>Print</td>
              <td>On</td>
              <td>ReactJS</td>
          </tr>
          <tr>
              <td>Test</td>
              <td>Print</td>
              <td>On</td>
              <td>ReactJS</td>
          </tr>
          <tr>
              <td>Test</td>
              <td>Print</td>
              <td>On</td>
              <td>ReactJS</td>
          </tr>
          <tr>
              <td>Test</td>
              <td>Print</td>
              <td>On</td>
              <td>ReactJS</td>
          </tr>
          <tr>
              <td>Test</td>
              <td>Print</td>
              <td>On</td>
              <td>ReactJS</td>
          </tr>
          <tr>
              <td>Test</td>
              <td>Print</td>
              <td>On</td>
              <td>ReactJS</td>
          </tr>
          <tr>
              <td>Test</td>
              <td>Print</td>
              <td>On</td>
              <td>ReactJS</td>
          </tr>
          <tr>
              <td>Test</td>
              <td>Print</td>
              <td>On</td>
              <td>ReactJS</td>
          </tr>
          <tr>
              <td>Test</td>
              <td>Print</td>
              <td>On</td>
              <td>ReactJS</td>
          </tr>
          <tr>
              <td>Test</td>
              <td>Print</td>
              <td>On</td>
              <td>ReactJS</td>
          </tr>
          <tr>
              <td>Test</td>
              <td>Print</td>
              <td>On</td>
              <td>ReactJS</td>
          </tr>
          <tr>
              <td>Test</td>
              <td>Print</td>
              <td>On</td>
              <td>ReactJS</td>
          </tr>
         
        </tbody>        
      </table>
    );
  }
}